
octopus:
  environments:
    - development
    - production
  development:
    postgres:
      host: localhost
      port: 5432
      adapter: postgresql
      database: laravel-etl

    mysql:
      adapter: mysql2
      database: hotel_mysql
      username: root
      password:

    sqlserver:
      adapter: sqlserver
      mode: dblib
      host: localhost
      port: 1433
      username: admin
      password:
      database: DWH

    mysql_etl:
      adapter: mysql2
      database: db/development_etl
      username: root
      password:

  production:
    shard_one:
      host: localhost
      adapter: mysql
      database: app_production
