
octopus:
  environments:
    - development

  development:
    rrhh:
      
      host: localhost
      port: 5432
      adapter: postgresql
      database: laravel-etl
      username: admin

    restaurant:
      adapter: mysql2
      database: hotel_mysql
      username: root
      password:

    dwh:
      adapter: sqlserver
      mode: dblib
      host: localhost
      port: 1433
      username: admin
      password:
      database: DWH

    dwh_t:
      adapter: mysql2
      database: DWH_tempory
      username: root
      password:
